#-------------------------------
# General Site Settings
title: "AIWC (AI 웹소설 코치)"
description: "AIWC와 함께 웹소설을 제작해 봅시다"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aiwc.kr" # the base hostname & protocol for your site, e.g. http://example.com

# 날짜 형식 설정
# minima:
#   date_format: "%Y-%m-%d"

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /blog/:slug/
  projects:
    output: true
    permalink: /project/:slug/
  categories:
    output: true
    permalink: /category/:name/

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

sass:
  sass_dir: _sass
  style: compressed