# =============================================================================
# HEEN THEME - CONTENT & UI SETTINGS (_data/settings.yml)
# =============================================================================
# 콘텐츠 및 UI 설정 (개발 서버 재시작 없이 변경 가능)

# ===================================
# 사이트 설정
# ===================================
title: 흰 (Heen)
description: "A modern Jekyll theme"
logo: "/assets/images/logo/logo.png"
logo_dark: "/assets/images/logo/logo-dark.png"
favicon: "/favicon.ico"
color_scheme: "auto"
brand_color: "#2563eb"
secondary_color: "#64748b"
tagline: "Modern Jekyll theme"
  
# ===================================
# 메인 네비게이션
# ===================================
navigation:
  main:
    - title: "Home"
      url: "/"
      icon: "fas fa-home"
    - title: "About"
      url: "/about/"
      icon: "fas fa-user"
    - title: "Projects"
      url: "/projects/"
      icon: "fas fa-briefcase"
    - title: "Blog"
      url: "/blog/"
      icon: "fas fa-blog"
    - title: "Contact"
      url: "/contact/"
      icon: "fas fa-envelope"
  
  mobile:
    - title: "Home"
      url: "/"
      icon: "fas fa-home"
    - title: "Projects"
      url: "/projects/"
      icon: "fas fa-briefcase"
    - title: "Blog"
      url: "/blog/"
      icon: "fas fa-blog"
    - title: "Contact"
      url: "/contact/"
      icon: "fas fa-envelope"

# ===================================
# 소셜 미디어 링크
# ===================================
social:
  github: "heen-theme"
  twitter: "heen_theme"
  linkedin: "heen-theme"
  instagram: "heen.theme"
  youtube: "@heen-theme"
  facebook: "heen.theme"
  email: "hello@heen-theme.com"

# ===================================
# 전역 기능 활성화/비활성화
# ===================================
features:
  back_to_top: true
  smooth_scroll: true
  reading_progress: true
  print_stylesheet: true
  search_highlight: true
  lazy_loading: true

# ===================================
# 블로그 설정
# ===================================
blog:
  show_excerpt: true
  excerpt_length: 160
  show_reading_time: true
  show_tags: true
  show_categories: true
  show_author: true
  related_posts: 3
  comments_enabled: true

# ===================================
# 프로젝트 설정
# ===================================
projects:
  show_categories: true
  show_tags: true
  grid_layout: 3
  show_featured: true
  featured_count: 6
  show_github_link: true

# ===================================
# 전역 기본 연락처 (푸터 등에서 사용)
# ===================================
site_contact:
  email: "hello@heen-theme.com"
  phone: "+82-10-1234-5678"
  address: "Seoul, South Korea"

# ===================================
# 푸터 설정
# ===================================
footer:
  copyright: "© 2024 Heen Theme. All rights reserved."
  links:
    - name: "Privacy Policy"
      url: "/privacy/"
    - name: "Terms of Service"
      url: "/terms/"
    - name: "Documentation"
      url: "/docs/"
    - name: "Support"
      url: "/support/"

# ===================================
# 댓글 시스템
# ===================================
comments:
  provider: "disqus"
  disqus_shortname: "heen-theme"
  giscus:
    repo: "heen-theme/heen-theme"
    repo_id: ""
    category: "General"
    category_id: ""

# ===================================
# 분석 도구
# ===================================
analytics:
  google_analytics: ""
  google_tag_manager: ""
  google_site_verification: ""

# ===================================
# 검색 기능
# ===================================
search:
  enabled: true
  provider: "lunr"
  placeholder: "Search posts and projects..."
  show_results_count: true

# ===================================
# 다크 모드
# ===================================
dark_mode:
  enabled: true
  default: "auto"
  toggle_position: "header"

# ===================================
# PWA 설정
# ===================================
pwa:
  enabled: false
  app_name: "Heen Theme"
  short_name: "Heen"
  theme_color: "#2563eb"
  background_color: "#ffffff"
  display: "standalone"

# ===================================
# 뉴스레터 구독
# ===================================
newsletter:
  enabled: false
  provider: "mailchimp"
  endpoint: ""
  title: "Stay Updated"
  description: "Get the latest updates and insights delivered to your inbox."

# ===================================
# 기능 토글 (전역 시스템 기능)
# ===================================
features:
  back_to_top: true
  smooth_scroll: true
  reading_progress: true
  print_stylesheet: true
  search_highlight: true
  lazy_loading: true
  image_optimization: true
  css_minification: true
  js_minification: true
  preload_fonts: true